name: Build and push project

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Load .env file for frontend
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VITE_URL: ${{ secrets.VITE_URL }}
          file_name: apps/front/.env

      - name: Load .env file for backend
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_TZ: ${{ secrets.TZ }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_HOST: ${{ secrets.HOST }}
          envkey_LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          envkey_APP_KEY: ${{ secrets.APP_KEY }}
          envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_DATABASE: ${{ secrets.DB_DATABASE }}
          file_name: apps/back/.env

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: cd apps/front && pnpm build

      - name: Build backend
        run: cd apps/back && pnpm build --ignore-ts-errors

      - name: Connect to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Copy frontend build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "apps/front/dist/*"
          target: "/home/melvincourant/htdocs/guildbattlemaster.com/"
          strip_components: 3

      - name: Copy backend build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "apps/back/build/*, apps/back/get_monsters.js"
          target: "/home/melvincourant/htdocs/guildbattlemaster.com/back/"
          strip_components: 3