name: Build and push project

on:
  push:
    branches:
      - main

jobs:
  back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name !== 'pull_request' }}
          tags: ghcr.io/MelvinCourant/guild-battle-master/back:latest
          target: back

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name !== 'pull_request' }}
          tags: ghcr.io/MelvinCourant/guild-battle-master/front:latest
          target: front

      - name: Deploy the new image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker service update --image ghcr.io/MelvinCourant/guild-battle-master/back:latest
            docker service update --image ghcr.io/MelvinCourant/guild-battle-master/front:latest